export const primaryBtn = "bg-ascents cursor-pointer text-white hover:bg-ascents-darker xl:px-20 lg:px-10 px-5 py-5 min-w-40 rounded-lg transition-all text-center text-xl"
export const secondaryBtn = "bg-white cursor-pointer border-2 border-ascents text-ascents hover:bg-ascents-darker hover:text-white text-center text-xl transition-all xl:px-20 lg:px-10 px-5 py-5 min-w-40 rounded-lg"
export const primaryBtnSM = "bg-ascents cursor-pointer text-white hover:bg-ascents-darker xl:px-20 lg:px-10 px-5 py-4 min-w-40 rounded-lg transition-all text-center"
export const secondaryBtnSM = "bg-white cursor-pointer border-2 border-ascents text-ascents hover:bg-ascents-darker hover:text-white text-center transition-all xl:px-20 lg:px-10 px-5 py-4 min-w-40 rounded-lg"
export const primaryBtnLG = "bg-ascents cursor-pointer text-white hover:bg-ascents-darker px-12 py-5 min-w-40 rounded-lg transition-all text-center text-xl"
